[tool.poetry]
name = "db"
version = "0.1.0"
description = "db"
authors = ["skwwnlpro <skwwnlpro@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pymongo = "^4.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
